# name = input("Enter your name:- ")
# age = input("Enter your age:- ")
# print("Hello " + name + "! You are " + age + " years old.")
# N=input("Enter the first number:- ")
# M=input("Enter the second number:- ")
# print("The sum is:",int(N)+int(M))
# print("The difference is:",int(N)-int(M))
# print("The product is:",int(N)*int(M))
# print("The quotient is:",int(N)/int(M))
# print("The remainder is:",int(N)%int(M))
# print("The power is:",int(N)**int(M))
print(ord("A"))
print(ord("a"))